### ISSUE TITLE
blog-cms项目 npm install安装依赖后跑不起来 98%

### ISSUE THREAD

**Issue by wzyhddy** [Naccl/NBlog#100]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/93774961/221184919-b343cd63-57a2-4358-9f3c-e8fea8f93ae0.png">

**Comment by wzyhddy** [comment]
node 14版本 15版本 16、18版本都试过了  也删除node_moudles了 不知道是哪的问题

**Comment by Naccl** [comment]
我这里无法复现哦，从这些错误日志也看不出来原因，建议先检查下依赖是否全部 install 成功了

**Comment by wzyhddy** [comment]
已解决，大佬牛逼！
