### ISSUE TITLE
首页接口数据出来了 跳转详情页数据没显示 什么也没有调动 直接源码的，数据库本地测试有数据

### ISSUE THREAD

**Issue by Axidada** [Naccl/NBlog#103]

**Comment by Axidada** [comment]
https://javajz.com/blog/256

**Comment by Axidada** [comment]
![image](https://user-images.githubusercontent.com/29518224/223385596-2ec73441-2ebd-4681-afa1-f26464cdc7e5.png)
![image](https://user-images.githubusercontent.com/29518224/223385694-11462883-0822-4ae4-a606-2a0fb1d283b8.png)

**Comment by Naccl** [comment]
你这是CORS啊，后端怎么部署的

**Comment by Axidada** [comment]
后端打包成jar  nohup java -jar ....&
![image](https://user-images.githubusercontent.com/29518224/223688537-11185296-03e9-41ec-a1ee-17103212f080.png)

**Comment by Axidada** [comment]
是不是我的服务器带不起来呢 卡死

**Comment by Naccl** [comment]
应该是nginx配置问题，能不能贴出全部的，我感觉你有个 location /blog/ 的配置

**Comment by Axidada** [comment]
![image](https://user-images.githubusercontent.com/29518224/223888381-23534225-380f-4b3e-9b4a-d6c4d903f1e0.png)
![image](https://user-images.githubusercontent.com/29518224/223888426-859abd08-af6a-4d63-ae4f-6573e11affc3.png)
![image](https://user-images.githubusercontent.com/29518224/223888469-96f6dcd1-a171-42ff-a2ba-58b4fd01d58e.png)
![image](https://user-images.githubusercontent.com/29518224/223888511-30aca20c-bcc1-4475-bd88-568dca3a46f7.png)

**Comment by Axidada** [comment]
是这个吗

**Comment by Axidada** [comment]
![image](https://user-images.githubusercontent.com/29518224/223909120-a5c18ea7-346d-44ff-8e25-1a82895f89bb.png)
我看了下报错 空指针

**Comment by Axidada** [comment]
![image](https://user-images.githubusercontent.com/29518224/223909257-3149abdc-4d46-4baf-8cac-87f33f0b62f9.png)

**Comment by Axidada** [comment]
现在好了 应该和我同步数据库有关 我还原最初始的数据库就可以了

**Comment by Axidada** [comment]
我的问题给第一个一样 我应该关闭程序  清空redis   之后在重启项目就可以了  本地我还原出来这个问题 之后我按照issues第一个里面 你说的
