### ISSUE TITLE
项目打包成镜像部署在服务器上，一段时间后异常停止

### ISSUE THREAD

**Issue by xiaoyuspace** [Naccl/NBlog#117]
哥哥你好，是这样的，我将后台blog-api打包成docker镜像，然后前端的前台和后台打包后，放在nginx上运行。刚开始运行很完美，一切可以正常访问，过一两天后我再去访问时发现请求失败，进服务器一看发现blog-api停止了，关闭。然后看日志发现的bug有两种，但是这两种bug都没有导致blog-api立即关闭，还能运行，一两天之后项目就自动关闭了。不晓得原因。
第一处bug如图：
![image](https://github.com/Naccl/NBlog/assets/102913022/5c6c2cc4-b556-48a4-b8d5-d462c9499b5c)
第二处bug如图：
![image](https://github.com/Naccl/NBlog/assets/102913022/252821cc-1ac4-4583-bcf0-c3cc3882884d)
项目最后的日志如图：
![image](https://github.com/Naccl/NBlog/assets/102913022/21b0c1f6-45a9-4ad2-a43c-86676188ca4a)
。大佬可以看看是怎么个事嘛

**Comment by Naccl** [comment]
第一个是quartz的非集群模式运行的正常提示，不是bug。
第二个一般是请求格式错误的错误日志，也不是bug。
第三个看不出来有啥问题，可能是OOM了？服务器的内存是多大，有没有调过JVM参数，可以试试在启动参数加上`-XX:+HeapDumpOnOutOfMemoryError`看看有没有dump文件。看起来是在执行定时任务后发生的，试下手动触发定时任务能不能复现。

**Comment by xiaoyuspace** [comment]
大佬你好，定时任务也没问题，经过大佬的这一番回答，我大概找到原因了，我服务器内存就2g,未调整过jvm参数，或许是oom了
