### ISSUE TITLE
sql 文件缺失system_setting表

### ISSUE THREAD

**Issue by 18554861841** [Naccl/NBlog#119]
作者大大，代码拉下来后发现表不全

**Comment by Naccl** [comment]
好像没有这个表吧，是不是看窜了

**Comment by 18554861841** [comment]
代码里有的
















在 2023-08-20 23:10:28，"Naccl Lu" ***@***.***> 写道：

好像没有这个表吧，是不是看窜了

**Comment by 18554861841** [comment]
[NBlog](https://github.com/Naccl/NBlog/tree/dev)/[blog-api](https://github.com/Naccl/NBlog/tree/dev/blog-api)/[src](https://github.com/Naccl/NBlog/tree/dev/blog-api/src)/[main](https://github.com/Naccl/NBlog/tree/dev/blog-api/src/main)/[java](https://github.com/Naccl/NBlog/tree/dev/blog-api/src/main/java)/[top](https://github.com/Naccl/NBlog/tree/dev/blog-api/src/main/java/top)/[naccl](https://github.com/Naccl/NBlog/tree/dev/blog-api/src/main/java/top/naccl)/[entity](https://github.com/Naccl/NBlog/tree/dev/blog-api/src/main/java/top/naccl/entity)
/SystemSetting.java
