### ISSUE TITLE
后台管理部署成功，但登陆账号密码错误

### ISSUE THREAD

**Issue by TangLight** [Naccl/NBlog#122]
![QHSUUB1Q F$3S%OF {F{MYL](https://github.com/Naccl/NBlog/assets/111823266/11826ac1-e21c-4ea3-98df-c16866e0c28b)
![5WCOA(}M_Z2WJR0F8QV(`3D](https://github.com/Naccl/NBlog/assets/111823266/c8559d88-b8ab-4e17-8fa0-e265a6caae09)
后台管理部署一切正常，但是登陆账号密码为什么总是错误啊，难道不是user表中的吗

**Comment by Naccl** [comment]
表中的是加密后的，你导入sql后用默认密码123456进去后在界面改

**Comment by TangLight** [comment]
现在注册账号我只能通过数据库添加账号，目前后台管理中只有修改，没有增删查，是否应该完善一下
![X RK6N@$CQQ7B9%)D3 OLQ](https://github.com/Naccl/NBlog/assets/111823266/fbbac0ad-573b-42c4-943a-e959edcf4220)
