### ISSUE TITLE
首图无法展示

### ISSUE THREAD

**Issue by WuQilins** [Naccl/NBlog#128]
![1711447040904](https://github.com/Naccl/NBlog/assets/164151294/4620cf0c-26ce-4ba5-aceb-e864a40c61d0)
![1711447070597](https://github.com/Naccl/NBlog/assets/164151294/210995fe-91fc-4b2e-b292-6e1f94976ed2)

请问前端这里是有代码缺少吗，为什么博客首图没有展示出来呢？

**Comment by walterke1001** [comment]
我也遇到这个问题了，文章首图显示不出来，请问你解决了吗
