### ISSUE TITLE
升级到springboot3 并使用graalvm native-image编译

### ISSUE THREAD

**Issue by mikechenczy** [Naccl/NBlog#131]
升级到springboot3 java17 并使用graalvm native-image编译，可以使程序性能大幅提升，内存占用下降。我使用手机linux deploy部署，由于是arm架构的cpu运行java会非常慢，很耗资源，所以native编译。编译成功，启动时间2秒，内存占用少了1g，响应速度也加快了。
升级springboot3，弃用了nl的ua库，修改了redis的核心为jedis，升级jwt、mysql、page等包；securityconfig需要整改，其他的只需要稍微修修补补。
我升级后的仓库：https://github.com/mikechenczy/blog-api

**Comment by Naccl** [comment]
维护阶段暂时没有升级重构的计划，可以给你 Pin 一下
