### ISSUE TITLE
富文本编辑器有问题

### ISSUE THREAD

**Issue by AnQiLaYa** [Naccl/NBlog#141]
上传根本没有走接口，导致刷新后无法显示的情况

**Comment by Naccl** [comment]
需要自行上传图床，没有上传服务器本地的功能

**Comment by AnQiLaYa** [comment]
我已经将该功能扩展了，如果您有需要请联系我
&nbsp;


Freeman
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Naccl ***@***.***&gt;; 
发送时间: 2024年8月20日(星期二) 中午11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Naccl/NBlog] 富文本编辑器有问题 (Issue #141)















需要自行上传图床，没有上传服务器本地的功能

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***&gt;
