### ISSUE TITLE
首页文章图片无法显示

### ISSUE THREAD

**Issue by walterke1001** [Naccl/NBlog#142]
![图片](https://github.com/user-attachments/assets/e03af2b1-5b31-41dd-8d16-4693a649821f)
这是我CMS中的设置
![图片](https://github.com/user-attachments/assets/bafcd25d-b09e-4406-b7d1-3b9cbf4f915a)
![图片](https://github.com/user-attachments/assets/bc2eebf0-6bcf-4627-bf16-768a0925ea21)
随机文章中的首图可以显示，但是首页文章的首图无法显示，请问这个是什么原因啊？是需要设置哪里吗？感谢作者大佬。

**Comment by JinhZz** [comment]
我也遇到了同样的问题，只有首页文章这里的图片无法显示

**Comment by walterke1001** [comment]
> 我也遇到了同样的问题，只有首页文章这里的图片无法显示

后端代码的问题，在加载图片时候会修改图片标签的属性，改了一下后端代码，不修改图片标签的属性就好了

**Comment by JinhZz** [comment]
> > 我也遇到了同样的问题，只有首页文章这里的图片无法显示
> 
> 后端代码的问题，在加载图片时候会修改图片标签的属性，改了一下后端代码，不修改图片标签的属性就好了

okok感谢，我修改了后端的修改图片属性那里，可以显示了

**Comment by JinhZz** [comment]
> > 我也遇到了同样的问题，只有首页文章这里的图片无法显示
> 
> 后端代码的问题，在加载图片时候会修改图片标签的属性，改了一下后端代码，不修改图片标签的属性就好了

想问一下大佬是修改了哪部分代码，我在修改MarkdownUtils里这部分代码后，文章内的图片又无法显示了
![Uploading 微信图片_20241111135503.png…]()

**Comment by JinhZz** [comment]
> > 我也遇到了同样的问题，只有首页文章这里的图片无法显示
> 
> 后端代码的问题，在加载图片时候会修改图片标签的属性，改了一下后端代码，不修改图片标签的属性就好了

想问一下大佬，是修改了哪部分代码我在修改MarkdownUtils这部分代码后，文章内的图片又无法显示了
![525fa5b6999a15dae69c8f2f086ab77](https://github.com/user-attachments/assets/9fb645f7-63c1-4c9a-81fa-99f69e002afa)

**Comment by walterke1001** [comment]
> > > 我也遇到了同样的问题，只有首页文章这里的图片无法显示
> > 
> > 
> > 后端代码的问题，在加载图片时候会修改图片标签的属性，改了一下后端代码，不修改图片标签的属性就好了
> 
> 想问一下大佬，是修改了哪部分代码？我在修改MarkdownUtils这部分代码后，文章内的图片又无法显示了 ![525fa5b6999a15dae69c8f2f086ab77](https://private-user-images.githubusercontent.com/162874077/384799941-9fb645f7-63c1-4c9a-81fa-99f69e002afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1Njc1NjksIm5iZiI6MTczMTU2NzI2OSwicGF0aCI6Ii8xNjI4NzQwNzcvMzg0Nzk5OTQxLTlmYjY0NWY3LTYzYzEtNGM5YS04MWZhLTk5ZjY5ZTAwMmFmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNjU0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDY4OGQ3NjNmNjlhNTgzYzJmNmM3ZjJmNDMxYmQyOWI3MWEyN2I3NDljMGEzOTM0YTllNDhiMzQ0OWQ4MzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NHlfks2OFRjqwpBX2ThIrYERSGqSK5BUUHWlLsdVkGk)

文章内的图片标签必须是markdown格式的，不能是html格式的

**Comment by Naccl** [comment]
抱歉，之前做懒加载的时候漏了这几个页面，现在已修复 dbf7a0521c26253af77b74383c5892139c72a394

拉取最新提交，后端代码不做改动，删除 redis 中 [homeBlogInfoList, friendInfoMap, aboutInfoMap] 三个 key 重启前端即可
