### ISSUE TITLE
异常错误

### ISSUE THREAD

**Issue by SingleLRS** [Naccl/NBlog#146]
为什么我发布的文章刚开始是ok的但是过一会就提示异常错误, 管理端与前台都无法展示

**Comment by SingleLRS** [comment]
但是每次重启后端即可解决

**Comment by Kaige3** [comment]
可以试一下在一些关键步骤自定义一些异常信息，比如，从redis获取views，或者是查询文章这些关键api，也可以试一下手动清理redis
你给的信息太少了，很难猜到哪里有问题

**Comment by SingleLRS** [comment]
![image](https://github.com/user-attachments/assets/669a11ac-5219-4984-8f8b-ddf48b5b7ba5)

**Comment by SingleLRS** [comment]
![image](https://github.com/user-attachments/assets/d883048d-d567-40e5-aac5-a04f474b3e24)

**Comment by SingleLRS** [comment]
请问大佬 这里是有什么问题嘛, 我并没有手动修改过MySql数据
