### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by chongtouxi** [Naccl/NBlog#38]
Access to XMLHttpRequest at 'http://localhost:8090/site' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:8090/site:1 Failed to load resource: net::ERR_FAILED
home:1 Access to XMLHttpRequest at 'http://localhost:8090/blogs' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:8090/blogs:1 Failed to load resource: net::ERR_FAILED
createError.js?2d83:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:117)
btpae.msdnt.com/api/goods/istart?id=istart:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

大佬这是怎么回事 要怎么解决

**Comment by Naccl** [comment]
CORS 跨域请求被浏览器阻止了

我在后端 [WebConfig](https://github.com/Naccl/NBlog/blob/8fe56ba23c196ce319d0743f6b07212a7b4c0822/blog-api/src/main/java/top/naccl/config/WebConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46)  中已经配置了支持跨域，正常不会出现这种情况，确认下是否修改过原本的代码？

**Comment by chongtouxi** [comment]
> CORS 跨域请求被浏览器阻止了
> 
> 我在后端 [WebConfig](https://github.com/Naccl/NBlog/blob/8fe56ba23c196ce319d0743f6b07212a7b4c0822/blog-api/src/main/java/top/naccl/config/WebConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46) 中已经配置了支持跨域，正常不会出现这种情况，确认下是否修改过原本的代码？

**Comment by chongtouxi** [comment]
> CORS 跨域请求被浏览器阻止了
> 
> 我在后端 [WebConfig](https://github.com/Naccl/NBlog/blob/8fe56ba23c196ce319d0743f6b07212a7b4c0822/blog-api/src/main/java/top/naccl/config/WebConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46) 中已经配置了支持跨域，正常不会出现这种情况，确认下是否修改过原本的代码？

会不会是后端的问题,我后端运行起来,一直报错 是如下的问题,前端的话没有改过,只有后端改了redis配置
 Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
Using generated security password: 8b8bd69e-4e44-42d4-a28e-6d59706daee7

> > CORS 跨域请求被浏览器阻止了
> > 我在后端 [WebConfig](https://github.com/Naccl/NBlog/blob/8fe56ba23c196ce319d0743f6b07212a7b4c0822/blog-api/src/main/java/top/naccl/config/WebConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46) 中已经配置了支持跨域，正常不会出现这种情况，确认下是否修改过原本的代码？



> CORS 跨域请求被浏览器阻止了
> 
> 我在后端 [WebConfig](https://github.com/Naccl/NBlog/blob/8fe56ba23c196ce319d0743f6b07212a7b4c0822/blog-api/src/main/java/top/naccl/config/WebConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46) 中已经配置了支持跨域，正常不会出现这种情况，确认下是否修改过原本的代码？



> CORS 跨域请求被浏览器阻止了
> 
> 我在后端 [WebConfig](https://github.com/Naccl/NBlog/blob/8fe56ba23c196ce319d0743f6b07212a7b4c0822/blog-api/src/main/java/top/naccl/config/WebConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46) 中已经配置了支持跨域，正常不会出现这种情况，确认下是否修改过原本的代码？

**Comment by chongtouxi** [comment]
会不会是后端的问题,我后端运行起来,一直报错 是如下的问题,前端的话没有改过,只有后端改了redis配置
 Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
Using generated security password: 8b8bd69e-4e44-42d4-a28e-6d59706daee7

**Comment by Naccl** [comment]
跟这个没有关系的，这个是 quartz 非集群启动的提示信息，不是报错

**Comment by chongtouxi** [comment]
那就是前端的问题了,我两个前端都进不去,前端代码没有改过,但就是会出现如下问题
blog-cms的问题
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
login:1 Access to XMLHttpRequest at 'http://localhost:8090/admin/login' from origin 'http://localhost:8079' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
request.js?4020:50 Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:117)
:8090/admin/login:1 Failed to load resource: net::ERR_FAILED
createError.js?2d83:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:117)

blog-view的问题
home:1 Access to XMLHttpRequest at 'http://localhost:8090/blogs' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:8090/blogs:1 Failed to load resource: net::ERR_FAILED
home:1 Access to XMLHttpRequest at 'http://localhost:8090/site' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
:8090/site:1 Failed to load resource: net::ERR_FAILED
createError.js?2d83:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:117)
btpae.msdnt.com/api/goods/istart?id=istart:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

**Comment by Naccl** [comment]
你换个浏览器试试吧，怀疑是你在浏览器设置了不安全的 http 自动转换到 https，建议先搜索一下错误信息

**Comment by chongtouxi** [comment]
还是不行,要裂开了,求求大佬救救,昨晚部署后端部署一个晚上,就差这个前端了

**Comment by Naccl** [comment]
所以你到底是在啥环境啊，部署还是本地？部署的话为啥是 localhost

**Comment by chongtouxi** [comment]
我就是想让项目在本地运行,然后就改了数据库,改成自己的数据库还有redis,其他啥都没改,我也不知道这算是啥环境

**Comment by Naccl** [comment]
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

根据你的这些报错，大概率是浏览器设置，或者本地代理问题，建议自查

**Comment by chongtouxi** [comment]
大佬,我查了一下,说是代码有一些自定义拦截器，Springboot处理的时候是有顺序问题的，配置mapping资源的时候，因为是先经过了拦截器，然后就出现了这个跨域问题,但是不知道怎么解决,搞了一天还是不会
