### ISSUE TITLE
关于blogId的问题

### ISSUE THREAD

**Issue by hnyk6** [Naccl/NBlog#39]
您好，克隆了您的博客项目后，在博客管理-写文章时显示异常错误。后台显示
POST(String), {"blog":{"id":2,"title":"test02","firstPicture":"https://wpimg.wallstcn.com/69a1c46c-eb1c-4b46-8bd4-e9e686ef5251.png","content":"好像是token的问题","description":"测试02，测试01好像失败了。。","published":true,"recommend":true,"appreciation":true,"commentEnabled":true,"top":false,"createTime":1641457628364,"updateTime":1641457628364,"views":0,"words":12,"readTime":0,"password":"","user":{"id":1,"username":null,"password":null,"nickname":null,"avatar":null,"email":null,"createTime":null,"updateTime":null,"role":null},"category":{"id":1,"name":"测试集","blogs":[]},"tags":[],"cate":1,"tagList":["02"]}}(String), 发布博客(String), org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: ****Parameter 'blogId' not found. Available parameters are [arg1, arg0, param1, param2]****
但数据库里确实是写入了，同时前端是可以看到文章的。
相应的还有后台管理博客也是显示不出的，比如找不到 title 字段。

**Comment by Naccl** [comment]
需要完整的错误信息，能否在后台管理的「异常日志」页面找到呢？
