### ISSUE TITLE
关于跨域问题

### ISSUE THREAD

**Issue by jackieword** [Naccl/NBlog#40]
请问有设计解决请求跨域的代码吗

**Comment by Naccl** [comment]
[WebConfig.java](https://github.com/Naccl/NBlog/blob/f55186023e9663bfce95350732ed8e6374acf836/blog-api/src/main/java/top/naccl/config/WebConfig.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46)

**Comment by jackieword** [comment]
为什么我打包blog-cms到docker nginx容器内后，api的接口测试是可以访问的，登录却一直提示net::ERR_CONNECTION_REFUSED

**Comment by Naccl** [comment]
此问题通常与本地配置或代理设置有关

首先应该检查
1. 前端配置`baseURL`, `http`, `port`是否正确
2. nginx 配置

以下回答可能有所帮助：

https://stackoverflow.com/questions/40931707/making-an-api-call-from-dockerized-web-page-to-back-end-server-ends-up-with-net
https://www.ionos.com/digitalguide/hosting/technical-matters/err-connection-refused/
