### ISSUE TITLE
请教作者

### ISSUE THREAD

**Issue by BOOMXU-BLACK** [Naccl/NBlog#62]
作者你好，请问可以用你的博客系统搭建一个自己的博客吗，以及我自己进行一些二次开发

**Comment by Naccl** [comment]
MIT 许可协议，除保留版权外无其它限制。

**Comment by BOOMXU-BLACK** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Naccl ***@***.***&gt;; 
发送时间: 2022年4月1日(星期五) 下午3:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Naccl/NBlog] 请教作者 (Issue #62)





 
MIT 许可协议，除保留版权外无其它限制。
