### ISSUE TITLE
首页访问异常

### ISSUE THREAD

**Issue by ox123** [Naccl/NBlog#64]
将代码直接clone下来打包编译丢在nginx中，然后远程访问首页，直接访问localhost
![image](https://user-images.githubusercontent.com/7547133/162557476-94a52b10-9de4-4592-ba6a-20aa3993f02d.png)

**Comment by Naccl** [comment]
需要将 `/src/plugins/axios.js` 中的 `baseUrl` 修改为你的后端 API 地址

后台管理 `/src/util/request.js` 同理
