### ISSUE TITLE
后台管理dashboard无法访问

### ISSUE THREAD

**Issue by duanyhui** [Naccl/NBlog#67]
在本地可以运行，放到服务器上就无法访问了，只有这个仪表盘没用，其他页面都正常，大佬求解答
![image](https://user-images.githubusercontent.com/91049287/162610698-36eab196-2e9e-4509-898a-34d7428aa275.png)
![image](https://user-images.githubusercontent.com/91049287/162610749-d7bac1df-1fab-4212-a53e-e578511e156f.png)
这是配置的信息
![image](https://user-images.githubusercontent.com/91049287/162610846-d0914612-7a72-4db0-843e-4dc98cda7f7a.png)
![image](https://user-images.githubusercontent.com/91049287/162610874-7d9baf8a-d551-424a-b916-2ca62e0beb54.png)

**Comment by Naccl** [comment]
Network 看看这个请求是否成功了，响应数据如何，有可能后端出现了异常，能否在「异常日志」页面找到对应的堆栈信息？

**Comment by duanyhui** [comment]
日志如图
![6F@380}N_23{DL}TQ6X0 2](https://user-images.githubusercontent.com/91049287/162615266-d401750f-f1b0-471e-aea1-57a609d870c0.png)
![W3SI_J(G0RD D6NW_71_OLJ](https://user-images.githubusercontent.com/91049287/162615271-b505dd81-e317-40b6-ac57-1f126deef7eb.png)



在mysql发现没有city_visitor这个表试图导入出现
![99 CGE4AF(2R$H4$A50B(~D](https://user-images.githubusercontent.com/91049287/162615296-37532f55-2781-4d3d-9c46-e5c08aef4f47.png)
。。。为啥其他表都能导入就这张表不行。。。

**Comment by Naccl** [comment]
这个表主键是 `city varchar(255)`，会创建主键索引，索引长度 `4 * 255 > 767`，所以报错了。

在 5.7 之后，[`innodb_large_prefix` 默认是开启的](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix)，可能你使用的 MySQL 版本在这之前，或是修改过这个变量为 `OFF`。

你要做的是将这个系统变量置为 `ON`，或者干脆将 `city varchar(255)` 改为 `city varchar(20)`，因为这个字段目前只会保存 ip2region 中的国内城市名，似乎没有哪个国内城市名超过 20 个字符，改了也无妨。

**Comment by duanyhui** [comment]
解决了，感谢大大
