### ISSUE TITLE
打包部署为war包异常

### ISSUE THREAD

**Issue by codetiger666** [Naccl/NBlog#68]
blog-api打包为war包后，部署到tomcat服务器，前端页面正常，前端后台一直报请登录，但是后端一直没有任何日志输出，使用jar包部署正常
![image](https://user-images.githubusercontent.com/37653895/163590771-f9646200-b298-4072-be9b-1e9d4ab422e4.png)

**Comment by codetiger666** [comment]
实际以登录成功，并且退出后再次登录依然报请登录

**Comment by Naccl** [comment]
看样子后端没收到 token，看下这个请求的 headers 中是否有 Authorization 呢

**Comment by codetiger666** [comment]
> 看样子后端没收到 token，看下这个请求的 headers 中是否有 Authorization 呢

token是有的，只要把后端换成jar包就正常了

**Comment by Naccl** [comment]
https://github.com/Naccl/NBlog/blob/f0ba7c9ff02887b8610c58053e47c3d1d88b5391/blog-api/src/main/java/top/naccl/config/JwtFilter.java#L38

可以在 39 行，简单打印一下后端是否真实收到了 token
```java
System.out.println("jwt:" + jwt);
```

如果是 null 的话，你可能需要检查下 tomcat 的配置

**Comment by codetiger666** [comment]
> https://github.com/Naccl/NBlog/blob/f0ba7c9ff02887b8610c58053e47c3d1d88b5391/blog-api/src/main/java/top/naccl/config/JwtFilter.java#L38
> 
> 可以在 39 行，简单打印一下后端是否真实收到了 token
> 
> ```java
> System.out.println("jwt:" + jwt);
> ```
> 
> 如果是 null 的话，可能在 tomcat 中被过滤掉了，需要你检查下 tomcat 的配置
> 
> > https://stackoverflow.com/questions/29973815/authentication-headers-with-jquery-and-tomcat/30002366#30002366
> > allowing cross-domain request :
> > ```
> > <filter>
> >   <filter-name>CorsFilter</filter-name>
> >   <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
> >   <init-param>
> >     <param-name>cors.allowed.origins</param-name>
> >     <param-value>*</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.allowed.methods</param-name>
> >     <param-value>GET,POST,HEAD,OPTIONS,PUT,DELETE</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.allowed.headers</param-name>
> >     <param-value>Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,authorization,Authorization,accept,Accept</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.support.credentials</param-name>
> >     <param-value>true</param-value>
> >   </init-param>
> > </filter>
> > <filter-mapping>
> >   <filter-name>CorsFilter</filter-name>
> >   <url-pattern>/*</url-pattern>
> > </filter-mapping>
> > ```

等下我试下

**Comment by codetiger666** [comment]
> https://github.com/Naccl/NBlog/blob/f0ba7c9ff02887b8610c58053e47c3d1d88b5391/blog-api/src/main/java/top/naccl/config/JwtFilter.java#L38
> 
> 可以在 39 行，简单打印一下后端是否真实收到了 token
> 
> ```java
> System.out.println("jwt:" + jwt);
> ```
> 
> 如果是 null 的话，可能在 tomcat 中被过滤掉了，需要你检查下 tomcat 的配置
> 
> > https://stackoverflow.com/questions/29973815/authentication-headers-with-jquery-and-tomcat/30002366#30002366
> > allowing cross-domain request :
> > ```
> > <filter>
> >   <filter-name>CorsFilter</filter-name>
> >   <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
> >   <init-param>
> >     <param-name>cors.allowed.origins</param-name>
> >     <param-value>*</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.allowed.methods</param-name>
> >     <param-value>GET,POST,HEAD,OPTIONS,PUT,DELETE</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.allowed.headers</param-name>
> >     <param-value>Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,authorization,Authorization,accept,Accept</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.support.credentials</param-name>
> >     <param-value>true</param-value>
> >   </init-param>
> > </filter>
> > <filter-mapping>
> >   <filter-name>CorsFilter</filter-name>
> >   <url-pattern>/*</url-pattern>
> > </filter-mapping>
> > ```

可以了，果然是tomcat的问题，被过滤了

**Comment by codetiger666** [comment]
> https://github.com/Naccl/NBlog/blob/f0ba7c9ff02887b8610c58053e47c3d1d88b5391/blog-api/src/main/java/top/naccl/config/JwtFilter.java#L38
> 
> 可以在 39 行，简单打印一下后端是否真实收到了 token
> 
> ```java
> System.out.println("jwt:" + jwt);
> ```
> 
> 如果是 null 的话，可能在 tomcat 中被过滤掉了，需要你检查下 tomcat 的配置
> 
> > https://stackoverflow.com/questions/29973815/authentication-headers-with-jquery-and-tomcat/30002366#30002366
> > allowing cross-domain request :
> > ```
> > <filter>
> >   <filter-name>CorsFilter</filter-name>
> >   <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
> >   <init-param>
> >     <param-name>cors.allowed.origins</param-name>
> >     <param-value>*</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.allowed.methods</param-name>
> >     <param-value>GET,POST,HEAD,OPTIONS,PUT,DELETE</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.allowed.headers</param-name>
> >     <param-value>Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,authorization,Authorization,accept,Accept</param-value>
> >   </init-param>
> >   <init-param>
> >     <param-name>cors.support.credentials</param-name>
> >     <param-value>true</param-value>
> >   </init-param>
> > </filter>
> > <filter-mapping>
> >   <filter-name>CorsFilter</filter-name>
> >   <url-pattern>/*</url-pattern>
> > </filter-mapping>
> > ```

还有个问题需要请教下，前端页面部署后，直接访问域名可以打开，点击各个页面也正常，但是只要刷新就会提示404，这个是啥问题

**Comment by Naccl** [comment]
其它问题重新开个 issue 吧，这样别人也能参考

**Comment by codetiger666** [comment]
我刚又试了一下。上午的时候是负载到我jar包上去了，war包依然不行，我找到问题了，是request.getRequestURI方法的问题，我提交了一个pull request，你可以看下，觉得没问题的话可以合并下，省的后面有人再遇到这个问题
