### ISSUE TITLE
前端打包部署后刷新报404

### ISSUE THREAD

**Issue by codetiger666** [Naccl/NBlog#69]
前端页面打包后部署到nginx,直接打开主页正常，点击各页面也正常，但是刷新就报404错误，直接打开除主页外的任何页面都报404错误

**Comment by Naccl** [comment]
我在 VueRouter 中使用的是 HTML5 History 模式，在服务器部署后，需要额外的配置支持。

参考官方文档 https://v3.router.vuejs.org/zh/guide/essentials/history-mode.html

另外，如需 Express + Node.js 的配置方法，可以参考 #63
