### ISSUE TITLE
使用虚拟主机可以吗

### ISSUE THREAD

**Issue by HaoJason** [Naccl/NBlog#76]
如果可以的话，配置要求是什么

**Comment by Naccl** [comment]
真是难倒我了。。。暂时认为你指的是「虚拟机」。
#53 意思是基本没有要求，只要是通用的，常见的硬件配置，都可以。

**Comment by xt962464** [comment]
虚拟主机应该不可以吧?这个需要运行java项目的,市面上的大多数虚拟主机都是不支持java的,除非你买的虚拟主机支持部署java项目,不过你买得起支持java的虚拟主机还不如买个服务器

**Comment by HaoJason** [comment]
好的，多谢
