### ISSUE TITLE
后端收到奇怪的请求地址导致项目崩溃

### ISSUE THREAD

**Issue by duanyhui** [Naccl/NBlog#83]
大大运行您的项目三个多月没有出现问题,最近项目突然崩溃终止,服务器上启动不了发现问题是cfworker的tg反代服务失效导致项目无法启动已解决,期间查项目日志发现项目崩溃前和之前运行中出现了一些奇怪的网址请求例如
![image](https://user-images.githubusercontent.com/91049287/181062670-d7c0c023-2cd0-4720-a0c6-b8c9298db229.png)

![image](https://user-images.githubusercontent.com/91049287/181062724-c5da0ae7-8901-4f0a-9f4a-4b08b9b7a302.png)
指向一些fd网站
![image](https://user-images.githubusercontent.com/91049287/181063022-1df2e0e4-bbd9-4fd1-b7ec-69b8efb44c2d.png)

希望大佬解答一下这是什么原因造成的
以下是崩溃前完整的日志
[blog-dev-2022-07-06-0.log](https://github.com/Naccl/NBlog/files/9191774/blog-dev-2022-07-06-0.log)

**Comment by Naccl** [comment]
看起来这是两个问题：
1. 启动时设置 tg 的 webhook，如果设置不成功则抛出异常终止服务启动，提醒自己配置出错，也是当时的设计目的。
2. 日志中奇怪的 URL，我也比较好奇为什么这些域名会指向你的服务，刚开始怀疑你的 nginx 配置可能有误，后面发现你的服务可以用 IP 访问，那么可能是 nginx 没拦截 IP 访问的请求，或者没有用 nginx 而直接用的 IP 访问。我猜这些网站的目的是想把 Error Page 指向你的 IP 来规避一些问题，那么被异常处理类抛出异常也很正常，这应该不会导致服务崩溃之类的问题。我的建议是无所谓，或者我的推断没错的话，上一层 nginx 应该能把这些请求拦截在服务之外。

**Comment by duanyhui** [comment]
感谢大大，我凌晨打字可能有点晕乎现在看这个语序看着我都头晕，
问题已解决，nginx配置这里应该怎么修改还得请教一下
另外我还挺好奇那天晚上这个项目的怎么挂掉的毕竟5月份cf就被墙了而我这个7月份才挂😂
![image](https://user-images.githubusercontent.com/91049287/181166236-62587455-6f3a-498a-b495-8c95248f98df.png)
![image](https://user-images.githubusercontent.com/91049287/181166242-638f5619-565f-4776-a7cb-728ae89f0ad9.png)

**Comment by Naccl** [comment]
看着没有问题，可以添加
```nginx
server {
        listen 80 default;
        server_name _;
        return 403;
}

server {
        listen 443 ssl default_server;
        server_name _;
        ssl_certificate     /your_pem.pem;
        ssl_certificate_key /your_key.key;
        return 403;
}
```
来过滤 IP 直接访问，但是我并不确定这样就不会出现日志中的情况🥲

另外如果那个日志文件就是挂之前最后的日志，我还是觉得服务挂了与日志中的内容没啥关联，可能帮不上啥忙了，或许可以看下 nginx log

**Comment by duanyhui** [comment]
十分感谢！
