### ISSUE TITLE
后台管理端出现图床预览bug

### ISSUE THREAD

**Issue by hyf-github-user** [Naccl/NBlog#85]
admin后台的前端中UpyunManage组件中有一个bug，预览的图片cdn链接不能正常显示应该为：imgCdnUrl(file) {
			return `http://${this.upyunConfig.domain}${this.imgPath(file)}`
		},
。还有一个问题就是在nginx部署cdn域名的ssl证书时应该怎样部署呀？望大哥发一个参考的。

**Comment by Naccl** [comment]
你的意思是URL前需要加上 `http://`，其实这个应该填在配置里的，因为我也不知道你要用 https 还是 http，需要自己配置的
![image](https://user-images.githubusercontent.com/44741777/181826355-a9909782-d7cd-44ae-88db-21143a186032.png)

cdn 的 ssl 不需要配到 nginx，因为是访问的又拍云，需要在又拍云的控制台配置
![image](https://user-images.githubusercontent.com/44741777/181827046-9fab85c8-fb24-4891-b9af-55ae8b771836.png)
