### ISSUE TITLE
未填写配置信息，直接访问腾讯云图床会报错

### ISSUE THREAD

**Issue by Raxcl** [Naccl/NBlog#94]
目前有一个bug，如果没有保存配置信息，就直接点击腾讯云图床界面，由于用到了 import，所以会初始化配置信息，但又没有配置信息，所以会出现异常，我不知道如何处理这部分逻辑（目前处理办法：如果误点了，手动刷新）

**Comment by Naccl** [comment]
0c1494f4de14601426ca37bf01936b536997578c

可能是个迟到的 fix 😂，有时间可以帮忙测试一下，thanks~

**Comment by Raxcl** [comment]
> [0c1494f](https://github.com/Naccl/NBlog/commit/0c1494f4de14601426ca37bf01936b536997578c)
> 
> 可能是个迟到的 fix 😂，有时间可以帮忙测试一下，thanks~

可以啦，原来是这么解决的，学到了
