### ISSUE TITLE
<meting-js>显示出了问题

### ISSUE THREAD

**Issue by hyf-github-user** [Naccl/NBlog#97]
前台的前端在显示meting-js标签时无法显示音乐，在动态和关于我页面都无法显示meting-js标签

**Comment by Naccl** [comment]
看起来是 MetingJS 的 API 挂了，可以参考下 [MetingJS 的 issues](https://github.com/metowolf/MetingJS/issues) 先自行搭建个服务替代下

**Comment by Naccl** [comment]
也可以暂时用我的 API 替代下，在
```html
<script src="./Meting.min.js"></script>
```
之前添加
```html
<script>var meting_api='https://api.naccl.top/meting/api?server=:server&type=:type&id=:id&auth=:auth&r=:r';</script>
```

**Comment by hyf-github-user** [comment]
老哥有如何自己搭建meting-js的api的相关教程吗？本人想学习一下

**Comment by Naccl** [comment]
详见 https://github.com/xizeyoupan/Meting-API
