### ISSUE TITLE
后端mybatis日志

### ISSUE THREAD

**Issue by hyf-github-user** [Naccl/NBlog#98]
请问在后端您是如何实现在控制台打印sql日志的？我看你的mybatis的配置文件中没有看到log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 这个配置，想请教您是如何实现

**Comment by Naccl** [comment]
https://github.com/Naccl/NBlog/blob/2078a83862e213243d2e3a91a5aeaae641ad5740/blog-api/src/main/resources/application-dev.properties#L26-L27

debug日志会打印SQL
